In [154]:
#reading the csv file in pandas
import pandas as pd
df = pd.read_csv('ZillowApartmens_msp.csv')
df

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link
0,0,Platform Apartments,"747 Hampden Ave, Saint Paul, MN 55114","$1,245 - 2,225",Studio - 2 Beds,https://www.apartments.com/platform-apartments...
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421","$950 - 2,763",Studio - 4 Beds,https://www.apartments.com/platform-apartments...
2,2,Moda on Raymond,"760 Raymond Ave, Saint Paul, MN 55114","$1,094 - 2,875",Studio - 2 Beds,https://www.apartments.com/platform-apartments...
3,3,The Collection at Highland Bridge,"800 Cretin Ave S, Saint Paul, MN 55116","$1,355 - 6,645",Studio - 2 Beds,https://www.apartments.com/platform-apartments...
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422","$1,225 - 2,764",Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...
...,...,...,...,...,...,...
478,478,Townhome for Rent,"3733 DuPont Ave S Minneapolis, MN 55409",NaN,NaN,https://www.apartments.com/the-lakes-residence...
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...
481,481,House for Rent,"2730 Glenhurst Ave Minneapolis, MN 55416",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/the-abbey-apartment...

In [155]:
#information about the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   483 non-null    int64
 1   apt_names    483 non-null    object
 2   apt_address  483 non-null    object
 3   apt_price    405 non-null    object
 4   apt_type     405 non-null    object
 5   apt_link     483 non-null    object
dtypes: int64(1), object(5)
memory usage: 22.8+ KB

In [156]:
#we have price ranges in apt_price column so splitting those columns
df[['apt_price','apt_price2']] = df['apt_price'].str.split('-',1, expand = True)

C:\Users\13203\AppData\Local\Temp\ipykernel_2440\2788401900.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['apt_price','apt_price2']] = df['apt_price'].str.split('-',1, expand = True)

In [157]:
#after splitting
df

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
0,0,Platform Apartments,"747 Hampden Ave, Saint Paul, MN 55114","$1,245",Studio - 2 Beds,https://www.apartments.com/platform-apartments...,"2,225"
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421",$950,Studio - 4 Beds,https://www.apartments.com/platform-apartments...,"2,763"
2,2,Moda on Raymond,"760 Raymond Ave, Saint Paul, MN 55114","$1,094",Studio - 2 Beds,https://www.apartments.com/platform-apartments...,"2,875"
3,3,The Collection at Highland Bridge,"800 Cretin Ave S, Saint Paul, MN 55116","$1,355",Studio - 2 Beds,https://www.apartments.com/platform-apartments...,"6,645"
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422","$1,225",Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,"2,764"
...,...,...,...,...,...,...,...
478,478,Townhome for Rent,"3733 DuPont Ave S Minneapolis, MN 55409",NaN,NaN,https://www.apartments.com/the-lakes-residence...,NaN
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
481,481,House for Rent,"2730 Glenhurst Ave Minneapolis, MN 55416",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/the-abbey-apartment...,NaN

In [164]:
#cleaning the data
df['apt_price'] = df['apt_price'].str.replace('$', '', regex=True)
df['apt_price'] = df['apt_price'].str.replace(',', '', regex=True)
df['apt_price2'] = df['apt_price2'].str.replace(',', '', regex=True)
df['apt_price'] = df['apt_price'].str.replace(' /mo', '', regex=True)
df['apt_price'] = df['apt_price'].str.replace('nan', '', regex=True)
df['apt_type'] = df['apt_type'].str.replace('NaN', '', regex=True)
df['apt_price'] = df['apt_price'].str.replace('NA', '', regex=True)
df

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
0,0,Platform Apartments,"747 Hampden Ave, Saint Paul, MN 55114",1245,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2225
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421",950,Studio - 4 Beds,https://www.apartments.com/platform-apartments...,2763
2,2,Moda on Raymond,"760 Raymond Ave, Saint Paul, MN 55114",1094,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2875
3,3,The Collection at Highland Bridge,"800 Cretin Ave S, Saint Paul, MN 55116",1355,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,6645
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422",1225,Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,2764
...,...,...,...,...,...,...,...
478,478,Townhome for Rent,"3733 DuPont Ave S Minneapolis, MN 55409",NaN,NaN,https://www.apartments.com/the-lakes-residence...,NaN
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
481,481,House for Rent,"2730 Glenhurst Ave Minneapolis, MN 55416",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/the-abbey-apartment...,NaN

In [165]:
#replacing the values so that to perfome operations on that column
df1 = df.replace({'apt_price': {'Call for Rent': ''}}, regex=True)
df1

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
0,0,Platform Apartments,"747 Hampden Ave, Saint Paul, MN 55114",1245,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2225
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421",950,Studio - 4 Beds,https://www.apartments.com/platform-apartments...,2763
2,2,Moda on Raymond,"760 Raymond Ave, Saint Paul, MN 55114",1094,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2875
3,3,The Collection at Highland Bridge,"800 Cretin Ave S, Saint Paul, MN 55116",1355,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,6645
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422",1225,Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,2764
...,...,...,...,...,...,...,...
478,478,Townhome for Rent,"3733 DuPont Ave S Minneapolis, MN 55409",NaN,NaN,https://www.apartments.com/the-lakes-residence...,NaN
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
481,481,House for Rent,"2730 Glenhurst Ave Minneapolis, MN 55416",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/the-abbey-apartment...,NaN

In [166]:
# convert string to an integer
df1['apt_price'] = pd.to_numeric(df1['apt_price'])
df1['apt_price2'] = pd.to_numeric(df1['apt_price2'])
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 483 entries, 0 to 482
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   483 non-null    int64
 1   apt_names    483 non-null    object
 2   apt_address  483 non-null    object
 3   apt_price    396 non-null    float64
 4   apt_type     405 non-null    object
 5   apt_link     483 non-null    object
 6   apt_price2   360 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 26.5+ KB

In [167]:
# fetching the properties lessesthan 1000$
bel_1000 = df1[df1['apt_price'] < 1000]
bel_1000

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421",950.0,Studio - 4 Beds,https://www.apartments.com/platform-apartments...,2763.0
5,5,Solhaus Apartments,"2428 Delaware St, Minneapolis, MN 55414",965.0,1-2 Beds,https://www.apartments.com/ratio-columbia-heig...,2180.0
14,14,Artistry on 10th,"95 S 10th St, Minneapolis, MN 55403",915.0,Studio - 2 Beds,https://www.apartments.com/the-collection-at-h...,3809.0
17,17,Jax Apartments,"2333 Jackson St NE, Minneapolis, MN 55418",950.0,Studio - 2 Beds,https://www.apartments.com/the-reeve-robbinsda...,2010.0
28,28,Lake Pointe,"3413-3433 53rd Ave N, Brooklyn Center, MN 55429",999.0,1 Bed,https://www.apartments.com/arcata-apartments-m...,1199.0
...,...,...,...,...,...,...,...
391,391,The Pavilion on Berry Apartments,"950 Jefferson Commons Cir, Saint Paul, MN 55114",709.0,2-4 Beds,https://www.apartments.com/lasalle-apartments-...,929.0
392,392,Highcrest Manor Apartments,"3605 37th Ave NE, Saint Anthony, MN 55421",975.0,1-2 Beds,https://www.apartments.com/lasalle-apartments-...,1250.0
394,394,Uptown West Apartments,"3150 Raleigh Ave, Saint Louis Park, MN 55416",915.0,Studio - 1 Bed,https://www.apartments.com/deco-265-minneapoli...,1035.0
395,395,Gateway Commons,"2850 Northway Dr, Brooklyn Center, MN 55430",900.0,Studio - 2 Beds,https://www.apartments.com/deco-265-minneapoli...,1350.0
396,396,Brittany Apartments,"3127 S Highway 100, Saint Louis Park, MN 55416",850.0,Studio - 2 Beds,https://www.apartments.com/deco-265-minneapoli...,1400.0

In [168]:
# fetching the properties greaterthan 1500$
above_1500 = df1[df1['apt_price'] > 1500]
above_1500

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
7,7,Arcata Apartments,"901 Xenia Ave S, Minneapolis, MN 55416",1590.0,Studio - 2 Beds,https://www.apartments.com/ratio-columbia-heig...,2725.0
11,11,Xenia Apartments,"770 Xenia Ave S, Minneapolis, MN 55416",1620.0,1-2 Beds,https://www.apartments.com/moda-on-raymond-sai...,3855.0
18,18,LAKEHAUS,"3100 W Lake St, Minneapolis, MN 55416",1685.0,1-2 Beds,https://www.apartments.com/the-reeve-robbinsda...,9063.0
24,24,Moment,"650 Portland Ave, Minneapolis, MN 55415",1577.0,Studio - 2 Beds,https://www.apartments.com/365-nicollet-minnea...,5272.0
29,29,The Aubrey,"4220-4230 Nicollet Ave, Minneapolis, MN 55409",2699.0,2 Beds,https://www.apartments.com/arcata-apartments-m...,NaN
...,...,...,...,...,...,...,...
399,399,3639 Stinson Blvd,"Minneapolis, MN 55418",2180.0,4 Beds,https://www.apartments.com/colfax-villas-i-min...,NaN
400,400,4745 Minnehaha Ave Unit 103,"Minneapolis, MN 55406",2200.0,2 Beds,https://www.apartments.com/colfax-villas-i-min...,NaN
401,401,1240 S 2nd St Unit 932,"Minneapolis, MN 55415",4250.0,3 Beds,https://www.apartments.com/cedars-94-minneapol...,NaN
402,402,3624 E 38th St Unit D,"Minneapolis, MN 55406",1645.0,2 Beds,https://www.apartments.com/cedars-94-minneapol...,NaN
404,404,6009 Xerxes Ave S,"Minneapolis, MN 55410",1700.0,2 Beds,https://www.apartments.com/rosa-apartments-mpl...,NaN

In [169]:
#fetching row in between range
df1.loc[df1['apt_price'].between(1500, 2000)]

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
7,7,Arcata Apartments,"901 Xenia Ave S, Minneapolis, MN 55416",1590.0,Studio - 2 Beds,https://www.apartments.com/ratio-columbia-heig...,2725.0
11,11,Xenia Apartments,"770 Xenia Ave S, Minneapolis, MN 55416",1620.0,1-2 Beds,https://www.apartments.com/moda-on-raymond-sai...,3855.0
18,18,LAKEHAUS,"3100 W Lake St, Minneapolis, MN 55416",1685.0,1-2 Beds,https://www.apartments.com/the-reeve-robbinsda...,9063.0
24,24,Moment,"650 Portland Ave, Minneapolis, MN 55415",1577.0,Studio - 2 Beds,https://www.apartments.com/365-nicollet-minnea...,5272.0
30,30,The Vicinity,"205 Park Ave, Minneapolis, MN 55415",1634.0,Studio - 2 Beds,https://www.apartments.com/arcata-apartments-m...,4475.0
31,31,1800 Lake,"1800 W Lake St, Minneapolis, MN 55408",1905.0,1-2 Beds,https://www.apartments.com/arcata-apartments-m...,3130.0
34,34,The Encore,"212 10th Ave S, Minneapolis, MN 55415",1837.0,Studio - 3 Beds,https://www.apartments.com/track-29-city-apart...,9268.0
35,35,Forte on the Park,"1125 S 2nd St, Minneapolis, MN 55415",1592.0,Studio - 2 Beds,https://www.apartments.com/track-29-city-apart...,7435.0
36,36,Ironclad Residential,"811 Washington Ave S, Minneapolis, MN 55415",1600.0,1-2 Beds,https://www.apartments.com/lpm-minneapolis-mn/...,4695.0
39,39,EXPO,"200 University Ave SE, Minneapolis, MN 55414",1625.0,1-3 Beds,https://www.apartments.com/lpm-minneapolis-mn/...,6995.0
41,41,Solhavn/Soltva/NOLO Flats,"815 N 2nd St, Minneapolis, MN 55401",1573.0,1-2 Beds,https://www.apartments.com/minneapolis-grand-a...,2846.0
44,44,Borealis,"721 N 1st St, Minneapolis, MN 55401",1985.0,1-2 Beds,https://www.apartments.com/xenia-apartments-mi...,3275.0
45,45,Gibson Apartments,"703 NE Central Ave, Minneapolis, MN 55414",1507.0,Studio - 2 Beds,https://www.apartments.com/xenia-apartments-mi...,4586.0
48,48,The Archive,"110 N 1st St, Minneapolis, MN 55401",1525.0,Studio - 2 Beds,https://www.apartments.com/hq-apartments-minne...,3595.0
52,52,The Elysian,"711 4th St SE, Minneapolis, MN 55414",1750.0,2-4 Beds,https://www.apartments.com/rafter-minneapolis-...,3995.0
56,56,Vesi,"730 1/2 N 1st St, Minneapolis, MN 55401",1760.0,1-2 Beds,https://www.apartments.com/artistry-on-10th-mi...,6065.0
57,57,Parkway Commons,"4141 W 31st St, Minneapolis, MN 55416",1790.0,Studio - 2 Beds,https://www.apartments.com/artistry-on-10th-mi...,1895.0
58,58,FreightYard Townhomes and Flats,"50 4th Ave N, Minneapolis, MN 55401",1515.0,1-2 Beds,https://www.apartments.com/artistry-on-10th-mi...,2205.0
60,60,The Abbott,"3401 W 44th St, Minneapolis, MN 55410",1575.0,1-2 Beds,https://www.apartments.com/lux-apartments-minn...,4850.0
65,65,Marquette Place,"1314 Marquette Ave, Minneapolis, MN 55403",1619.0,1-4 Beds,https://www.apartments.com/daymark-uptown-minn...,5288.0
66,66,222 Hennepin,"222 Hennepin Ave, Minneapolis, MN 55401",1540.0,Studio - 2 Beds,https://www.apartments.com/daymark-uptown-minn...,3275.0
86,86,The Beach Club Residences,"2900 Thomas Ave S, Minneapolis, MN 55416",1565.0,Studio - 4 Beds,https://www.apartments.com/240-park-avenue-min...,10019.0
109,109,Landsby on Penn,"6200 Penn Ave S, Richfield, MN 55423",1635.0,Studio - 3 Beds,https://www.apartments.com/excelsior-grand-sai...,4001.0
110,110,Elan West End,"1325 Utica Ave S, Saint Louis Park, MN 55416",1781.0,Studio - 3 Beds,https://www.apartments.com/excelsior-grand-sai...,2975.0
112,112,CE Flats,"2410 W University Ave W, Saint Paul, MN 55114",1544.0,Studio - 2 Beds,https://www.apartments.com/lake-pointe-brookly...,9205.0
117,117,Marshall Lofts,"2105 Marshall Ave, Saint Paul, MN 55104",1895.0,2-3 Beds,https://www.apartments.com/the-aubrey-minneapo...,3975.0
118,118,Verge,"3601 Park Center Blvd, Saint Louis Park, MN 55416",1520.0,1-2 Beds,https://www.apartments.com/the-aubrey-minneapo...,12387.0
132,132,Phoenix North Loop,"915 Washington Ave N, Minneapolis, MN 55401",1599.0,1-2 Beds,https://www.apartments.com/22-on-the-river-min...,2999.0
144,144,Central Park West,"1511 Utica Ave S, Saint Louis Park, MN 55416",1605.0,Studio - 2 Beds,https://www.apartments.com/ironclad-residentia...,4915.0
153,153,Risor St. Louis Park - Active Adult 55+,"3510 Beltline Blvd, Minneapolis, MN 55416",1695.0,1-3 Beds,https://www.apartments.com/expo-minneapolis-mn...,5060.0
159,159,724 Lofts,"724 N 1st St, Minneapolis, MN 55401",1695.0,2-3 Beds,https://www.apartments.com/the-duffey-minneapo...,3195.0
163,163,New Boston Square,"2015 NE Central Ave, Minneapolis, MN 55418",1725.0,2 Beds,https://www.apartments.com/solhavn-soltva-nolo...,1775.0
170,170,Talo,"5100 Wayzata Blvd, Minneapolis, MN 55416",1682.0,Studio - 3 Beds,https://www.apartments.com/maverick-north-loop...,5792.0
197,197,One Southdale Place,"6800 York Ave S, Edina, MN 55435",1595.0,Studio - 3 Beds,https://www.apartments.com/the-station-at-malc...,3600.0
198,198,Parkway 25,"4015 Highway 25, Saint Louis Park, MN 55416",1730.0,1-2 Beds,https://www.apartments.com/the-station-at-malc...,1750.0
199,199,Ellipse on Excelsior and E2,"3920 Excelsior Blvd, Saint Louis Park, MN 55416",1640.0,Studio - 2 Beds,https://www.apartments.com/the-station-at-malc...,2720.0
200,200,The Flats at West End,"5310 W 16th St, Saint Louis Park, MN 55416",1545.0,Studio - 2 Beds,https://www.apartments.com/one-ten-grant-minne...,2825.0
206,206,The Lucy Apartments | St. Paul,"2069 Marshall Ave, Saint Paul, MN 55104",1540.0,1-2 Beds,https://www.apartments.com/the-nic-on-fifth-mi...,1995.0
210,210,Lyndale Plaza Apartments,"6401 Lyndale Ave S, Richfield, MN 55423",1700.0,2-3 Beds,https://www.apartments.com/the-bohen-minneapol...,2200.0
230,230,Volo at Texa Tonka,"7920 Minnetonka blvd, Minneapolis, MN 55426",1554.0,1-2 Beds,https://www.apartments.com/hencen-minneapolis-...,3340.0
231,231,1101 on Main Apartment Homes,"1101 Main St NE, Minneapolis, MN 55413",1545.0,1-2 Beds,https://www.apartments.com/hencen-minneapolis-...,2100.0
247,247,East Bank Village Apartments | NEWLY RENOV...,"22 University Ave, Minneapolis, MN 55413",1530.0,1-3 Beds,https://www.apartments.com/sela-campus-univers...,2010.0
264,264,4800 Excelsior,"4800 Excelsior Blvd, Saint Louis Park, MN 55416",1575.0,Studio - 2 Beds,https://www.apartments.com/good-dwelling-minne...,2670.0
265,265,The Westfield,"4415 Valley View Rd, Edina, MN 55424",1899.0,1-2 Beds,https://www.apartments.com/laurel-village-minn...,2595.0
290,290,The Original at West Lake Quarter,"3430 List Plz, Minneapolis, MN 55416",1820.0,Studio - 3 Beds,https://www.apartments.com/humboldt-terrace-mi...,3960.0
301,301,Second Street Lofts,"129 N 2nd St, Minneapolis, MN 55401",1620.0,1-2 Beds,https://www.apartments.com/elan-uptown-minneap...,2535.0
314,314,The Copham,"607 N Washington Ave, Minneapolis, MN 55401",1793.0,1-2 Beds,https://www.apartments.com/the-venue-on-knox-m...,2465.0
319,319,633 Ontario St SE,"Minneapolis, MN 55414",1900.0,3 Beds,https://www.apartments.com/foundry-lake-street...,NaN
324,324,SECOND AND SECOND,"120 2nd St N, Minneapolis, MN 55401",1735.0,1-2 Beds,https://www.apartments.com/the-asher-minneapol...,3682.0
375,375,Villa Capri,"3043 Inglewood Ave S, Saint Louis Park, MN 55416",1725.0,2 Beds,https://www.apartments.com/loring-park-minneap...,NaN
378,378,Cornelia Place,"4025 W 65th St, Edina, MN 55435",1595.0,1-2 Beds,https://www.apartments.com/rivergate-apartment...,NaN
398,398,4860 Park Commons Dr Unit 204,"Minneapolis, MN 55416",1895.0,2 Beds,https://www.apartments.com/colfax-villas-i-min...,NaN
402,402,3624 E 38th St Unit D,"Minneapolis, MN 55406",1645.0,2 Beds,https://www.apartments.com/cedars-94-minneapol...,NaN
403,403,2015 Lyndale Ave S Unit 205.990934,"Minneapolis, MN 55405",1500.0,Studio,https://www.apartments.com/cedars-94-minneapol...,NaN
404,404,6009 Xerxes Ave S,"Minneapolis, MN 55410",1700.0,2 Beds,https://www.apartments.com/rosa-apartments-mpl...,NaN

In [170]:
# apartment names contains minneapolis
df1[df1['apt_names'].str.contains('Minneapolis')]

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
10,10,Minneapolis Grand Apartments,"2401 Chicago Ave, Minneapolis, MN 55404",1050.0,Studio - 2 Beds,https://www.apartments.com/moda-on-raymond-sai...,1670.0
106,106,Yugo Minneapolis Sydney Hall,"308 15th Ave SE, Minneapolis, MN 55414",649.0,Studio - 4 Beds,https://www.apartments.com/york-place-apartmen...,2118.0
215,215,Student | HERE Minneapolis,"2813 4th St SE, Minneapolis, MN 55414",1279.0,Studio - 2 Beds,https://www.apartments.com/tree-tops-minneapol...,2409.0
357,357,Hub Minneapolis,"311 Harvard St SE, Minneapolis, MN 55414",670.0,Studio - 4 Beds,https://www.apartments.com/luna-minneapolis-mn...,1935.0

In [171]:
# apartments in minneapolis(zip:55414)
df1[df1['apt_address'].str.contains('55414')]

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
5,5,Solhaus Apartments,"2428 Delaware St, Minneapolis, MN 55414",965.0,1-2 Beds,https://www.apartments.com/ratio-columbia-heig...,2180.0
13,13,Rafter,"333 E Hennepin Ave, Minneapolis, MN 55414",1255.0,Studio - 3 Beds,https://www.apartments.com/the-collection-at-h...,8765.0
33,33,22 on the River,"22 27th Ave SE, Minneapolis, MN 55414",912.0,Studio - 2 Beds,https://www.apartments.com/track-29-city-apart...,2698.0
39,39,EXPO,"200 University Ave SE, Minneapolis, MN 55414",1625.0,1-3 Beds,https://www.apartments.com/lpm-minneapolis-mn/...,6995.0
45,45,Gibson Apartments,"703 NE Central Ave, Minneapolis, MN 55414",1507.0,Studio - 2 Beds,https://www.apartments.com/xenia-apartments-mi...,4586.0
50,50,The Station at Malcolm Yards,"485 Malcolm Ave SE, Minneapolis, MN 55414",1100.0,Studio - 2 Beds,https://www.apartments.com/hq-apartments-minne...,2395.0
52,52,The Elysian,"711 4th St SE, Minneapolis, MN 55414",1750.0,2-4 Beds,https://www.apartments.com/rafter-minneapolis-...,3995.0
59,59,Hencen,"455 Central Ave SE, Minneapolis, MN 55414",1195.0,Studio - 2 Beds,https://www.apartments.com/artistry-on-10th-mi...,3250.0
64,64,Sela Campus University Apartments,"701 University Ave SE, Minneapolis, MN 55414",1049.0,1 Bed,https://www.apartments.com/daymark-uptown-minn...,NaN
106,106,Yugo Minneapolis Sydney Hall,"308 15th Ave SE, Minneapolis, MN 55414",649.0,Studio - 4 Beds,https://www.apartments.com/york-place-apartmen...,2118.0
137,137,East River Terrace,"2101 E River Ter, Minneapolis, MN 55414",895.0,Studio - 2 Beds,https://www.apartments.com/the-encore-minneapo...,1150.0
148,148,Moerty Apartments,"821 6th Ave SE, Minneapolis, MN 55414",1295.0,Studio - 1 Bed,https://www.apartments.com/smyth-lofts-luxury-...,1595.0
152,152,Marko Apartments- Pre-leasing for Fall 2023,"711 8th St SE, Minneapolis, MN 55414",1250.0,Studio - 1 Bed,https://www.apartments.com/laguna-apartments-m...,1850.0
156,156,Coze Flats,"628 University Ave SE, Minneapolis, MN 55414",1096.0,Studio - 1 Bed,https://www.apartments.com/expo-minneapolis-mn...,1395.0
161,161,Spectrum Apartments,"815 9th Ave SE, Minneapolis, MN 55414",1295.0,1-4 Beds,https://www.apartments.com/solhavn-soltva-nolo...,3275.0
173,173,Brook Avenue Housing Cooperative,"1220 Brook Ave SE, Minneapolis, MN 55414",1079.0,Studio - 3 Beds,https://www.apartments.com/borealis-minneapoli...,2495.0
182,182,Fieldhouse,"805 15th Ave SE, Minneapolis, MN 55414",699.0,1-5 Beds,https://www.apartments.com/red-20-apartments-m...,1630.0
187,187,The Marshall,"515 14th Ave SE, Minneapolis, MN 55414",735.0,1-4 Beds,https://www.apartments.com/walkway-minneapolis...,1330.0
189,189,Fourth Street Cooperative,"1227 4th St SE, Minneapolis, MN 55414",749.0,1-3 Beds,https://www.apartments.com/the-archive-minneap...,2699.0
215,215,Student | HERE Minneapolis,"2813 4th St SE, Minneapolis, MN 55414",1279.0,Studio - 2 Beds,https://www.apartments.com/tree-tops-minneapol...,2409.0
220,220,The Endurance,"725 8th St SE, Minneapolis, MN 55414",1190.0,Studio - 1 Bed,https://www.apartments.com/vesi-minneapolis-mn...,1295.0
227,227,Dover Apartments,"515-527 5th Ave SE, Minneapolis, MN 55414",1495.0,2-3 Beds,https://www.apartments.com/freightyard-townhom...,2300.0
228,228,Flats at Malcolm Yards,"445 SE Malcolm Ave, Minneapolis, MN 55414",NaN,Studio,https://www.apartments.com/freightyard-townhom...,NaN
251,251,Stadium Village Apartments,"1015 Essex St SE, Minneapolis, MN 55414",835.0,Studio - 2 Beds,https://www.apartments.com/marquette-place-min...,1450.0
258,258,University Village,"2515 University Ave SE, Minneapolis, MN 55414",519.0,1-4 Beds,https://www.apartments.com/variant-minneapolis...,2030.0
276,276,525 Tenth Dinkytown Apartments Student Rental,"525 10th Ave SE, Minneapolis, MN 55414",1250.0,1-5 Beds,https://www.apartments.com/the-miles-uptown-mi...,3200.0
278,278,The Knoll,"1101 University Ave SE, Minneapolis, MN 55414",1380.0,Studio,https://www.apartments.com/the-paxon-minneapol...,NaN
279,279,700 Central Historic Lofts & New Flats,"700 NE Central Ave, Minneapolis, MN 55414",1365.0,Studio - 2 Beds,https://www.apartments.com/the-paxon-minneapol...,2735.0
286,286,Thornton Place Apartments,"810 SE Thornton St, Minneapolis, MN 55414",1400.0,1-2 Beds,https://www.apartments.com/zeo-minneapolis-mn/...,1425.0
289,289,Archer,"401 University Ave SE, Minneapolis, MN 55414",1250.0,Studio - 1 Bed,https://www.apartments.com/humboldt-terrace-mi...,1400.0
297,297,MPA / Marcy Park Apartments,"1015 8th St, Minneapolis, MN 55414",1225.0,1-4 Beds,https://www.apartments.com/the-shale-minneapol...,2650.0
306,306,Dinkytown Apartments,"519 10th Ave SE, Minneapolis, MN 55414",900.0,1-2 Beds,https://www.apartments.com/3828-apartments-min...,1180.0
317,317,The Denn of Dinkytown,"815 13th Ave SE, Minneapolis, MN 55414",975.0,1 Bed,https://www.apartments.com/aberdeen-apartments...,1000.0
319,319,633 Ontario St SE,"Minneapolis, MN 55414",1900.0,3 Beds,https://www.apartments.com/foundry-lake-street...,NaN
322,322,621 5th Ave.,"621 5th Ave SE, Minneapolis, MN 55414",900.0,1-2 Beds,https://www.apartments.com/foundry-lake-street...,1180.0
323,323,The Arrow Apartments - Student Housing,"117 27th Ave SE, Minneapolis, MN 55414",739.0,1-4 Beds,https://www.apartments.com/the-asher-minneapol...,1339.0
327,327,Oliver & Wendell Apartments,"600 University Ave SE, Minneapolis, MN 55414",1295.0,1-3 Beds,https://www.apartments.com/lago-apartments-min...,1615.0
329,329,Prospect Park Apartments,"3109 4th St SE, Minneapolis, MN 55414",850.0,Studio - 1 Bed,https://www.apartments.com/lago-apartments-min...,950.0
342,342,Como Court,"1005 15th Ave SE, Minneapolis, MN 55414",999.0,Studio - 2 Beds,https://www.apartments.com/dock-street-flats-m...,1399.0
343,343,Doyle Apartments,"1307 4th St SE, Minneapolis, MN 55414",650.0,1-4 Beds,https://www.apartments.com/flux-apartments-min...,3500.0
344,344,The Remington Campus Apartments,"708 5th St Se, Minneapolis, MN 55414",745.0,Studio - 2 Beds,https://www.apartments.com/flux-apartments-min...,1200.0
346,346,St. Anthony Village,"320 7th St SE, Minneapolis, MN 55414",800.0,Studio - 2 Beds,https://www.apartments.com/flux-apartments-min...,1240.0
351,351,The Brownstones,"800 4th St SE, Minneapolis, MN 55414",599.0,1-5 Beds,https://www.apartments.com/pure-lowry-minneapo...,2995.0
352,352,The Bridges,"930 University Ave SE, Minneapolis, MN 55414",615.0,Studio - 2 Beds,https://www.apartments.com/pure-lowry-minneapo...,1630.0
357,357,Hub Minneapolis,"311 Harvard St SE, Minneapolis, MN 55414",670.0,Studio - 4 Beds,https://www.apartments.com/luna-minneapolis-mn...,1935.0
366,366,Stone Arch I,"601-701 Main St SE, Minneapolis, MN 55414",1048.0,Studio - 2 Beds,https://www.apartments.com/rex26-minneapolis-m...,1758.0
435,435,House for Rent,"2215 Cole Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/astor-place-of-edin...,NaN
460,460,Apartment for Rent,"1709 Como Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/ray-saint-paul-mn/p...,NaN
470,470,Apartment for Rent,"301 5th St SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/novo-apartments-ric...,NaN
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/311-kenwood-apartme...,NaN
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",NaN,NaN,https://www.apartments.com/the-abbey-apartment...,NaN

In [172]:
#checking for apartments in minneapolis(zip:55414) and also with apartment price greater than 1700
df1[(df1['apt_address'].str.contains('55401')) & (df1['apt_price'] > 1700.0)]

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
44,44,Borealis,"721 N 1st St, Minneapolis, MN 55401",1985.0,1-2 Beds,https://www.apartments.com/xenia-apartments-mi...,3275.0
56,56,Vesi,"730 1/2 N 1st St, Minneapolis, MN 55401",1760.0,1-2 Beds,https://www.apartments.com/artistry-on-10th-mi...,6065.0
314,314,The Copham,"607 N Washington Ave, Minneapolis, MN 55401",1793.0,1-2 Beds,https://www.apartments.com/the-venue-on-knox-m...,2465.0
324,324,SECOND AND SECOND,"120 2nd St N, Minneapolis, MN 55401",1735.0,1-2 Beds,https://www.apartments.com/the-asher-minneapol...,3682.0

In [173]:
#creating a new dataframe by replacing NaN values to beds in apt_type column
df2=df1.fillna('Beds')

In [174]:
#reading the new dataframe
df2

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
0,0,Platform Apartments,"747 Hampden Ave, Saint Paul, MN 55114",1245.0,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2225.0
1,1,Ratio,"909 Gould Ave NE, Columbia Heights, MN 55421",950.0,Studio - 4 Beds,https://www.apartments.com/platform-apartments...,2763.0
2,2,Moda on Raymond,"760 Raymond Ave, Saint Paul, MN 55114",1094.0,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,2875.0
3,3,The Collection at Highland Bridge,"800 Cretin Ave S, Saint Paul, MN 55116",1355.0,Studio - 2 Beds,https://www.apartments.com/platform-apartments...,6645.0
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422",1225.0,Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,2764.0
...,...,...,...,...,...,...,...
478,478,Townhome for Rent,"3733 DuPont Ave S Minneapolis, MN 55409",Beds,Beds,https://www.apartments.com/the-lakes-residence...,Beds
479,479,House for Rent,"3342 Prospect Terrace SE Minneapolis, MN 55414",Beds,Beds,https://www.apartments.com/311-kenwood-apartme...,Beds
480,480,Townhome for Rent,"819 Weeks Ave SE Minneapolis, MN 55414",Beds,Beds,https://www.apartments.com/311-kenwood-apartme...,Beds
481,481,House for Rent,"2730 Glenhurst Ave Minneapolis, MN 55416",Beds,Beds,https://www.apartments.com/311-kenwood-apartme...,Beds
482,482,House for Rent,"1078 11th Ave SE Minneapolis, MN 55414",Beds,Beds,https://www.apartments.com/the-abbey-apartment...,Beds

In [175]:
#checking the apatments with 3 bed rooms
df2[df2['apt_type'].str.contains('3')]

,Unnamed: 0,apt_names,apt_address,apt_price,apt_type,apt_link,apt_price2
4,4,The Reeve,"4600 Lake Road Ave, Robbinsdale, MN 55422",1225.0,Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,2764.0
6,6,365 Nicollet,"365 Nicollet Mall, Minneapolis, MN 55401",1292.0,Studio - 3 Beds,https://www.apartments.com/ratio-columbia-heig...,10779.0
9,9,LPM,"1369 Spruce Pl, Minneapolis, MN 55403",1209.0,Studio - 3 Beds,https://www.apartments.com/moda-on-raymond-sai...,6025.0
12,12,HQ Apartments,"816 Portland Ave S, Minneapolis, MN 55404",1075.0,Studio - 3 Beds,https://www.apartments.com/the-collection-at-h...,4580.0
13,13,Rafter,"333 E Hennepin Ave, Minneapolis, MN 55414",1255.0,Studio - 3 Beds,https://www.apartments.com/the-collection-at-h...,8765.0
...,...,...,...,...,...,...,...
341,341,Lowry Row Homes,"2407 2nd St NE, Minneapolis, MN 55418",2375.0,2-3 Beds,https://www.apartments.com/dock-street-flats-m...,Beds
349,349,The Birchway Apartments,"5716-5720 Winnetka Ave N, Minneapolis, MN 55428",1135.0,1-3 Beds,https://www.apartments.com/3848-west-broadway-...,1815.0
376,376,Aria,"3200 Southdale Cir, Edina, MN 55435",2043.0,Studio - 3 Beds,https://www.apartments.com/loring-park-minneap...,9282.0
390,390,Henley Apartments,"6324 S Lyndale Ave, Richfield, MN 55423",1150.0,Studio - 3 Beds,https://www.apartments.com/lasalle-apartments-...,2150.0
401,401,1240 S 2nd St Unit 932,"Minneapolis, MN 55415",4250.0,3 Beds,https://www.apartments.com/cedars-94-minneapol...,Beds